// Translations for things rendered in the main process (receipt + PDF report).
// Kept separate from the renderer dictionary because main runs in its own bundle.
const M = {
  en: {
    receipt: { total: 'TOTAL', subtotal: 'Subtotal', discount: 'Discount', change: 'Change', tel: 'Tel', table: 'Table', order: 'Order', cash: 'Cash', card: 'Card' },
    report: {
      salesReport: 'Sales report', for: 'For', generated: 'Generated', generatedBy: 'Generated by',
      revenue: 'Revenue', orders: 'Orders', avgOrder: 'Avg order', salesTrend: 'Sales trend — by {unit}', day: 'day', month: 'month',
      period: 'Period', topProducts: 'Top products', product: 'Product', qty: 'Qty', revenueCol: 'Revenue',
      salesByServer: 'Sales by server', server: 'Server', payments: 'Payments', method: 'Method', collected: 'Collected',
      changeGiven: 'Change given', noSales: 'No sales in this range.', noData: 'No data.', allStaff: 'All staff', cash: 'Cash', card: 'Card', other: 'Other',
      today: 'Today', thisWeek: 'This week', thisMonth: 'This month', thisYear: 'This year', allTime: 'All time'
    }
  },
  fr: {
    receipt: { total: 'TOTAL', subtotal: 'Sous-total', discount: 'Remise', change: 'Monnaie', tel: 'Tél', table: 'Table', order: 'Commande', cash: 'Espèces', card: 'Carte' },
    report: {
      salesReport: 'Rapport des ventes', for: 'Pour', generated: 'Généré', generatedBy: 'Généré par',
      revenue: 'Revenus', orders: 'Commandes', avgOrder: 'Panier moyen', salesTrend: 'Tendance des ventes — par {unit}', day: 'jour', month: 'mois',
      period: 'Période', topProducts: 'Meilleurs produits', product: 'Produit', qty: 'Qté', revenueCol: 'Revenus',
      salesByServer: 'Ventes par serveur', server: 'Serveur', payments: 'Paiements', method: 'Méthode', collected: 'Encaissé',
      changeGiven: 'Monnaie rendue', noSales: 'Aucune vente sur cette période.', noData: 'Aucune donnée.', allStaff: 'Tout le personnel', cash: 'Espèces', card: 'Carte', other: 'Autre',
      today: 'Aujourd’hui', thisWeek: 'Cette semaine', thisMonth: 'Ce mois', thisYear: 'Cette année', allTime: 'Tout'
    }
  },
  ar: {
    receipt: { total: 'الإجمالي', subtotal: 'المجموع الفرعي', discount: 'الخصم', change: 'الباقي', tel: 'هاتف', table: 'طاولة', order: 'طلب', cash: 'نقدًا', card: 'بطاقة' },
    report: {
      salesReport: 'تقرير المبيعات', for: 'لـ', generated: 'أُنشئ', generatedBy: 'أُنشئ بواسطة',
      revenue: 'الإيرادات', orders: 'الطلبات', avgOrder: 'متوسط الطلب', salesTrend: 'اتجاه المبيعات — حسب {unit}', day: 'يوم', month: 'شهر',
      period: 'الفترة', topProducts: 'أفضل المنتجات', product: 'المنتج', qty: 'الكمية', revenueCol: 'الإيرادات',
      salesByServer: 'المبيعات حسب الموظف', server: 'الموظف', payments: 'المدفوعات', method: 'الطريقة', collected: 'المحصّل',
      changeGiven: 'الباقي المُعاد', noSales: 'لا مبيعات في هذه الفترة.', noData: 'لا بيانات.', allStaff: 'كل الموظفين', cash: 'نقدًا', card: 'بطاقة', other: 'أخرى',
      today: 'اليوم', thisWeek: 'هذا الأسبوع', thisMonth: 'هذا الشهر', thisYear: 'هذه السنة', allTime: 'كل الوقت'
    }
  }
}

const resolve = (dict, key) => key.split('.').reduce((o, k) => (o == null ? undefined : o[k]), dict)

// mt(lang, 'report.revenue', { unit: 'day' }) → localized string, English fallback.
export function mt(lang, key, vars) {
  const dict = M[lang] || M.en
  let s = resolve(dict, key)
  if (s == null) s = resolve(M.en, key)
  if (s == null) return key
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v))
  return s
}

export const isRtlLang = (lang) => lang === 'ar'
